[package]
name = "reqlang-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-lsp = { version = "0.19.0" }
anyhow = "1.0.52"
tokio = { version = "1.17.0", features = ["io-std", "rt"] }
