[package]
name = "assert-response"
version = "0.1.0"
edition = "2021"

[dependencies]
types = { path = "../types" }
serde = { version = "1.0.195", features = ["derive"] }
similar = { version = "2.7.0" }
console = "0.15.10"

[dev-dependencies]
pretty_assertions = "1.4.1"
