[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
reqlang = { path = "../reqlang" }

[dev-dependencies]
pretty_assertions = "1.1.0"
rstest = "0.19.0"
tokio = { version = "1.17.0", features = ["macros"] }
